version: "3.8"

services:
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    command: --init-file /db_queries/init.sql
    volumes:
      - ./init.sql:/db_queries/init.sql
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  backend:
    image: backend
    depends_on:
      - mysqldb
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  frontend:
    image: frontend
    depends_on:
      - mysqldb
      - backend
    ports:
      - 80:80
    stdin_open: true
    tty: true

volumes:
  db-config:
  db-data:
